/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.orders;

import controller.OrderController;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Order;
import model.OrderDetail;
import model.Response;
//import model.database.Connect;
//import model.database.Staff;
//import swing.UIController;
//import utilities.File;
//import view.main.librarian.ReaderPanel;
//import static view.main.librarian.ReaderPanel.hash;

/**
 *
 * @author Admin
 */
public class OrderPanel extends javax.swing.JPanel {

    public final int DANG_GIAO = 3;
    public final int DA_HUY = 5;
    private DefaultTableModel dtmOrder;
    private DefaultTableModel dtmProduct;
    private OrderController oc;

    private enum Mode {
        ADD,
        MODIFY,
        FREE
    }
    private Mode mode;
    private HistoryDialog history;

    /**
     * Creates new form StaffPanel
     */
    public OrderPanel() {
        initComponents();
        oc = new OrderController();
        dtmProduct = (DefaultTableModel) jTable_Product.getModel();
        dtmOrder = (DefaultTableModel) jTable_Order.getModel();

        loadData(1);
        setEditableForAll(false);
    }

    public void loadData(int statusId) {
        List<Order> list = oc.getOrderByStatusId(statusId);
        oc.loadTable(list, dtmOrder);
        jTextField_ID.setText("");
        jTextField_User.setText("");
        jTextField_Price.setText("");
        jTextField_Date.setText("");
        dtmProduct.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_User = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Product = new javax.swing.JTable();
        jTextField_Date = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Order = new javax.swing.JTable();
        jButton_History = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton_DaHuy = new javax.swing.JRadioButton();
        jRadioButton_YeuCauHuy = new javax.swing.JRadioButton();
        jRadioButton_ChoXacNhan = new javax.swing.JRadioButton();
        jRadioButton_DangGiao = new javax.swing.JRadioButton();
        jRadioButton_DaGiao = new javax.swing.JRadioButton();
        jDateChooser_Search = new com.toedter.calendar.JDateChooser();
        jPanel_Card3 = new javax.swing.JPanel();
        jButton_Yes = new javax.swing.JButton();
        jButton_No = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order detail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Order ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Username");

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_User.setEditable(false);
        jTextField_User.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Total price");

        jTextField_Price.setEditable(false);
        jTextField_Price.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Date");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("VNĐ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Products", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jTable_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Product);
        if (jTable_Product.getColumnModel().getColumnCount() > 0) {
            jTable_Product.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable_Product.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable_Product.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField_Date.setEditable(false);
        jTextField_Date.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jTextField_User)
                            .addComponent(jTextField_Date)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))))
                .addGap(73, 73, 73)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Search:");

        jTable_Order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Username", "Total price", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_OrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Order);
        if (jTable_Order.getColumnModel().getColumnCount() > 0) {
            jTable_Order.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jButton_History.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_History.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/history.png"))); // NOI18N
        jButton_History.setText("History");
        jButton_History.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_History.setFocusPainted(false);
        jButton_History.setPreferredSize(new java.awt.Dimension(300, 60));
        jButton_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HistoryActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jRadioButton_DaHuy.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_DaHuy);
        jRadioButton_DaHuy.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_DaHuy.setText("Canceled");
        jRadioButton_DaHuy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_DaHuyStateChanged(evt);
            }
        });

        jRadioButton_YeuCauHuy.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_YeuCauHuy);
        jRadioButton_YeuCauHuy.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_YeuCauHuy.setText("Request cancellation");
        jRadioButton_YeuCauHuy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_YeuCauHuyStateChanged(evt);
            }
        });

        jRadioButton_ChoXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_ChoXacNhan);
        jRadioButton_ChoXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_ChoXacNhan.setSelected(true);
        jRadioButton_ChoXacNhan.setText("Being processed");
        jRadioButton_ChoXacNhan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_ChoXacNhanStateChanged(evt);
            }
        });

        jRadioButton_DangGiao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_DangGiao);
        jRadioButton_DangGiao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_DangGiao.setText("Delivering");
        jRadioButton_DangGiao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_DangGiaoStateChanged(evt);
            }
        });

        jRadioButton_DaGiao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_DaGiao);
        jRadioButton_DaGiao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_DaGiao.setText("Delivered");
        jRadioButton_DaGiao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_DaGiaoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_ChoXacNhan)
                    .addComponent(jRadioButton_YeuCauHuy))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton_DangGiao)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_DaGiao))
                    .addComponent(jRadioButton_DaHuy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_ChoXacNhan)
                    .addComponent(jRadioButton_DangGiao)
                    .addComponent(jRadioButton_DaGiao))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_YeuCauHuy)
                    .addComponent(jRadioButton_DaHuy))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jDateChooser_Search.setDate(new java.util.Date());
        jDateChooser_Search.setDateFormatString("dd-MM-yyyy");
        jDateChooser_Search.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jDateChooser_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateChooser_SearchMouseEntered(evt);
            }
        });
        jDateChooser_Search.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jDateChooser_SearchCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jDateChooser_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser_SearchKeyReleased(evt);
            }
        });

        jPanel_Card3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card3.setMaximumSize(new java.awt.Dimension(30000, 33));
        jPanel_Card3.setPreferredSize(new java.awt.Dimension(439, 30));
        jPanel_Card3.setLayout(new java.awt.GridLayout(0, 1, 35, 35));

        jButton_Yes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Yes.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Check.png"))); // NOI18N
        jButton_Yes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Yes.setMaximumSize(new java.awt.Dimension(95, 30));
        jButton_Yes.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_YesActionPerformed(evt);
            }
        });
        jPanel_Card3.add(jButton_Yes);

        jButton_No.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_No.setForeground(new java.awt.Color(51, 51, 51));
        jButton_No.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        jButton_No.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_No.setMaximumSize(new java.awt.Dimension(95, 33));
        jButton_No.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NoActionPerformed(evt);
            }
        });
        jPanel_Card3.add(jButton_No);

        jButton_Search.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Search)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_History, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jPanel_Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setEditableForAll(boolean editable) {
//        jDateChooser_DateOfBirth.setEnabled(editable);
//        jTextField_Name.setEditable(editable);
//        jTextField_PhoneNumber.setEditable(editable);
//        jTextField_Email.setEditable(editable);
//        jComboBox_Province.setEnabled(editable);
//        jComboBox_District.setEnabled(editable);
//        jComboBox_Commune.setEnabled(editable);
//        jComboBox_Role.setEnabled(editable);
    }

    private void jTable_OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_OrderMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_Product.convertRowIndexToModel(jTable_Order.getSelectedRow());
        String id = jTable_Order.getValueAt(selectedRow, 0).toString();

        jTextField_ID.setText(id);
        jTextField_User.setText(jTable_Order.getValueAt(selectedRow, 1).toString());
        jTextField_Price.setText(jTable_Order.getValueAt(selectedRow, 2).toString());
        jTextField_Date.setText(jTable_Order.getValueAt(selectedRow, 3).toString());

        List<OrderDetail> list = oc.getOrderDetailByOrderId(Integer.parseInt(id));
        oc.loadProductTable(list, dtmProduct);
    }//GEN-LAST:event_jTable_OrderMouseClicked

    private void jButton_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HistoryActionPerformed
        history = new HistoryDialog(null, true);
//        history.setIngredientList(ingredientList);
//        history.setProviderList(providerList);
//        history.addRowsToHistoryTable(ingredientList);
//        UIControl.setLocationCenterForDialog(history);
        history.setVisible(true);
    }//GEN-LAST:event_jButton_HistoryActionPerformed

    private void jButton_YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_YesActionPerformed
        // TODO add your handling code here:
        String id = jTextField_ID.getText();
        if (id.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "There is no selected item");
            return;
        }

        int result = JOptionPane.showConfirmDialog(this, "Are you sure?");
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        int orderId = Integer.parseInt(id);
        if (jRadioButton_ChoXacNhan.isSelected()) {
            Response res = oc.updateOrderByID(orderId, DANG_GIAO);
            JOptionPane.showMessageDialog(null, res.getMessage());
            if (res.getResponseCode() == 200) {
                loadData(1);
            } else {
                return;
            }
        }

        if (jRadioButton_YeuCauHuy.isSelected()) {
            Response res = oc.updateOrderByID(orderId, DA_HUY);
            JOptionPane.showMessageDialog(null, res.getMessage());
            if (res.getResponseCode() == 200) {
                loadData(2);
            } else {
                return;
            }
        }
    }//GEN-LAST:event_jButton_YesActionPerformed

    private void jButton_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NoActionPerformed
        // TODO add your handling code here:
        String id = jTextField_ID.getText();
        if (id.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "There is no selected item");
            return;
        }

        int result = JOptionPane.showConfirmDialog(this, "Are you sure?");
        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        int orderId = Integer.parseInt(id);
        if (jRadioButton_ChoXacNhan.isSelected()) {
            Response res = oc.updateOrderByID(orderId, DA_HUY);
            JOptionPane.showMessageDialog(null, res.getMessage());
            if (res.getResponseCode() == 200) {
                loadData(1);
            } else {
                return;
            }
        }

        if (jRadioButton_YeuCauHuy.isSelected()) {
            Response res = oc.updateOrderByID(orderId, DANG_GIAO);
            JOptionPane.showMessageDialog(null, res.getMessage());
            if (res.getResponseCode() == 200) {
                loadData(2);
            } else {
                return;
            }
        }
    }//GEN-LAST:event_jButton_NoActionPerformed

    public void setEnabledButton(boolean b) {
        jButton_Yes.setEnabled(b);
        jButton_No.setEnabled(b);
    }

    private void jRadioButton_ChoXacNhanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_ChoXacNhanStateChanged
        // TODO add your handling code here:

        if (jRadioButton_ChoXacNhan.isSelected()) {
            filter("");
            loadData(1);
            setEnabledButton(true);
        }
    }//GEN-LAST:event_jRadioButton_ChoXacNhanStateChanged

    private void jRadioButton_DangGiaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_DangGiaoStateChanged
        // TODO add your handling code here:

        if (jRadioButton_DangGiao.isSelected()) {
            filter("");
            loadData(3);
            setEnabledButton(false);
        }
    }//GEN-LAST:event_jRadioButton_DangGiaoStateChanged

    private void jRadioButton_DaGiaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_DaGiaoStateChanged
        // TODO add your handling code here:

        if (jRadioButton_DaGiao.isSelected()) {
            filter("");
            loadData(4);
            setEnabledButton(false);
        }
    }//GEN-LAST:event_jRadioButton_DaGiaoStateChanged

    private void jRadioButton_YeuCauHuyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_YeuCauHuyStateChanged
        // TODO add your handling code here:

        if (jRadioButton_YeuCauHuy.isSelected()) {
            filter("");
            loadData(2);
            setEnabledButton(true);
        }
    }//GEN-LAST:event_jRadioButton_YeuCauHuyStateChanged

    private void jRadioButton_DaHuyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_DaHuyStateChanged
        // TODO add your handling code here:

        if (jRadioButton_DaHuy.isSelected()) {
            filter("");
            loadData(5);
            setEnabledButton(false);
        }
    }//GEN-LAST:event_jRadioButton_DaHuyStateChanged

    private void jDateChooser_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser_SearchKeyReleased
        // TODO add your handling code here:
        System.out.println("key released");
    }//GEN-LAST:event_jDateChooser_SearchKeyReleased

    private void jDateChooser_SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser_SearchMouseEntered
        // TODO add your handling code here:
        System.out.println("mouse entered");
    }//GEN-LAST:event_jDateChooser_SearchMouseEntered

    private void jDateChooser_SearchCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooser_SearchCaretPositionChanged
        // TODO add your handling code here:
        System.out.println("caret position");
    }//GEN-LAST:event_jDateChooser_SearchCaretPositionChanged

    public void filter(String str) {
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_Order.getModel());
        jTable_Order.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str, 3));
    }

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String date = sdf.format(jDateChooser_Search.getDate());
        filter(date);
    }//GEN-LAST:event_jButton_SearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_History;
    private javax.swing.JButton jButton_No;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Yes;
    private com.toedter.calendar.JDateChooser jDateChooser_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Card3;
    private javax.swing.JRadioButton jRadioButton_ChoXacNhan;
    private javax.swing.JRadioButton jRadioButton_DaGiao;
    private javax.swing.JRadioButton jRadioButton_DaHuy;
    private javax.swing.JRadioButton jRadioButton_DangGiao;
    private javax.swing.JRadioButton jRadioButton_YeuCauHuy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Order;
    private javax.swing.JTable jTable_Product;
    private javax.swing.JTextField jTextField_Date;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Price;
    private javax.swing.JTextField jTextField_User;
    // End of variables declaration//GEN-END:variables
}
